### ISSUE TITLE
vcgencmd is still run on non raspberry pi devices

### ISSUE THREAD

**Issue by rahul-thakoor** [balena-io-playground/xserver#11]
https://github.com/balenablocks/xserver/blob/fb2250ce8a768f32da33c7fc48f2a99b887624fb/src/entry.sh#L13

E.g on x64 device:

```
[Logs]    [9/28/2021, 15:34:50] [browser] /opt/xserver/entry.sh: 16: vcgencmd: not found
[Logs]    [9/28/2021, 15:34:50] [browser] /opt/xserver/entry.sh: 16: [: Illegal number:
```

**Comment by jamwest** [comment]
Having messed about with this I think it is due to using ENTRYPOINT in the Dockerfile.template file. When running in shell the shebang is not being respected. I believe this is also causing the cursor toggle issues some people are experiencing.

**Comment by lukasknutti** [comment]
is there a known fix for this? or some more explanation of what might cause this bug? (using an Intel NUC here)

**Comment by nucleardreamer** [comment]
@jamwest you are 100% correct here! Sometimes it's the small things that are very easily overlooked. I tested just replacing `sh` with `bash` on the `ENTRYPOINT` and it works as expected. I will be publishing a new version shortly. 

@lukasknutti @jamwest @rahul-thakoor thank you guys for the patience on this issue, I know it's been a number of months!
