### ISSUE TITLE
Cursor Environment Variable is not toggling

### ISSUE THREAD

**Issue by gardlt** [balena-io-playground/xserver#9]
When using the `CURSOR` environment variable is set to `false` or `true` the cursor is still showing on the screen. 

It seems that the xserver's  `xinitrc` is not loaded correctly.

**Comment by nucleardreamer** [comment]
Hi @gardlt , I wasn't able to reproduce that (by changing env vars in the compose file). How are you setting environment variables right now?

I made a branch that changes the `xinitrc` script to add a bash shebang line, maybe the script wasn't correctly converting the variable check into a string? Why don't you go ahead and try it out to tell me if you see a difference: https://github.com/balenablocks/xserver/tree/cursor-variable-toggle

**Comment by gardlt** [comment]
I try to deploy these changes and the cursor is still showing. 

We are currently running 
*balenaOS* : `balenaOS 2.83.18+rev1`
*Release*: `Production`

I found a workaround that does work, by updating the `entry.sh`

**Comment by ngmartins** [comment]
CURSOR env var doesn't toggle for me as well.
A tried both: docker-compose and balena portal defenition.

**Comment by ngmartins** [comment]
I think it is because it is hardcoded on Dockerfile.template file.

**Comment by nucleardreamer** [comment]
@ngmartins the `CURSOR` variable is set in the Dockerfile as the default option, it will be overridden if set anywhere else

**Comment by nucleardreamer** [comment]
I am unable to reproduce this issue at all still. Setting `CURSOR` in the docker-compose.yml, on balena dashboard device or fleet variables all have the same result. 

For anyone seeing this, it's important to make sure you have all capitol `CURSOR` as the environment name, and no quotes around `true` or `false` values.
